spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/task-tracker"
    username: ""
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
